<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#c9a54d" stroke="#9c803c" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
  <path d="M14 2v4a2 2 0 0 0 2 2h4" fill="#9c803c" fill-opacity="0.3" />
  <!-- Symbol: Makefile (M shape) -->
  <path d="M9 18v-6l3 3 3-3v6" fill="none" stroke-width="1.5" />
</svg>
